version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    image: inception_nginx_dayo
    container_name: nginx
    ports:
      - "2525:443"
    volumes:
      - wordpress_sites:/var/www/html
    depends_on:
      - wordpress
    networks:
      - frontend
  wordpress:
    image: wordpress:6.4.2-php8.1-fpm
    restart: always
    ports:
      - 9000:80
    volumes:
      - wordpress_sites:/var/www/html
    networks:
      - frontend
      - backend
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
  db:
    build:
      context: ./mariadb
      dockerfile: ./Dockerfile
    image: inception_mariadb_dayo
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  wordpress_sites:
  db_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge