version: "3"
services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    image: inception_nginx_dayo
    container_name: nginx
    ports:
      - "2525:443"
    volumes:
      - wordpress_sites:/var/www/html
    depends_on:
      - wordpress
    networks:
      - frontend
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
    image: inception_wordpress_dayo
    restart: always
    ports:
      - 9000:80
    volumes:
      - wordpress_sites:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: db
      WP_DATA_PATH: /var/www/html
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_EDITOR_USER: ${WP_EDITOR_USER}
      WP_EDITOR_PASSWORD: ${WP_EDITOR_PASSWORD}
      WP_EDITOR_EMAIL: ${WP_EDITOR_EMAIL}
  db:
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    image: inception_mariadb_dayo
    restart: always
    ports:
      - 3306:3306
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mariadb", "-h", "db", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  wordpress_sites:
    driver_opts:
      o: bind
      device: ${WP_VOLUME_DIR}
      type: none
  db_data:
    driver: local
    driver_opts:
      o: bind
      device: ${DB_VOLUME_DIR}
      type: none

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
