version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    image: inception_nginx_dayo
    container_name: nginx
    ports:
      - "2525:443"
    volumes:
      - ./nginx/tools/html:/usr/share/nginx/html