version: "3"
services:
  nginx:
    # image: nginx:latest
    build:
      context: ./nginx
      dockerfile: .
    container_name: nginx
    ports:
      - "1024:1024"
    volumes:
      - ./nginx/tools/html:/usr/share/nginx/html